---
version: "3.5"
services:
  wizarr:
    container_name: wizarr
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5690:5690
    volumes:
      - ./database:/data/database # Change this to your data directory
    environment:
      - APP_URL=https://wizarr.example.com # Change this to your domain
      - DISABLE_BUILTIN_AUTH=false # Set to true to disable built-in authentication
      - TZ=Europe/London # Set your timezone