name: CI/CD Build Docker [Beta]

on:
    push:
        tags:
            - "v*.*.*-beta.*"
            - "*"
    workflow_dispatch:
        inputs:
            tag:
                description: "Tag"
                required: true

permissions:
    packages: write
    contents: write

env:
    GHCR_REGISTRY: ghcr.io
    DH_REGISTRY: docker.io
    IMAGE_NAME: wizarrrr/wizarr
    IMAGE_TAG: beta

jobs:
    before_build:
        name: Prepare for Build
        runs-on: ubuntu-latest
        steps:
            # Clear the digests from the artifacts
            - name: Clear digests
              uses: geekyeggo/delete-artifact@v2
              with:
                  name: |
                      digests_dh
                      digests_ghcr

    build:
        name: Build Digest for Registry
        runs-on: ubuntu-latest
        needs:
            - before_build
        strategy:
            fail-fast: false
            matrix:
                platform:
                    - linux/amd64
                    - linux/arm64

        steps:
            # Checkout the repo
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.workflow_run.head_branch }}

            # Use NPM and Node.js to install dependencies
            - name: Use Node.js 18.18.2
              uses: actions/setup-node@v2
              with:
                  node-version: 18.18.2

            # Set up Python and install Poetry
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            # Install Poetry
            - name: Install Poetry
              run: |
                  pip install poetry==1.6.1
                  poetry config virtualenvs.create false

            # Install dependencies
            - name: Install dependencies
              run: npm install

            # Build the Repository
            - name: Build the Repository
              run: |
                  npx nx build wizarr-backend
                  npx nx build wizarr-frontend

            # Set up Docker Buildx
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            # Login to GHCR
            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.GHCR_REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            # Build and push the image
            - name: Build and push by digest
              id: build
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./dockerfiles/wizarr-ci/Dockerfile
                  push: true
                  platforms: ${{ matrix.platform }}
                  provenance: false
                  outputs: type=image,name=${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }},push-by-digest=true,name-canonical=true

            # Export the digest for later use
            - name: Export digest
              run: |
                  mkdir -p /tmp/digests
                  digest="${{ steps.build.outputs.digest }}"
                  touch "/tmp/digests/${digest#sha256:}"

            # Upload the digest as an artifact
            - name: Upload digest
              uses: actions/upload-artifact@v3
              with:
                  name: digests_ghcr
                  path: /tmp/digests/*
                  if-no-files-found: error
                  retention-days: 1

    merge:
        name: Merge Digest to Registry
        runs-on: ubuntu-latest
        needs:
            - build
        steps:
            # Checkout the repo
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.workflow_run.head_branch }}

            # Get the Release Version from latest
            - name: Get the Release Version from latest
              id: get_version
              run: echo "::set-output name=version::$(cat latest)"

            # Download the digests from the artifacts
            - name: Download digests
              uses: actions/download-artifact@v3
              with:
                  name: digests_ghcr
                  path: /tmp/digests

            # Set up Docker Buildx
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            # Login to GHCR
            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            # Login to Docker Hub
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.DH_REGISTRY }}
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            # Get the tag name
            - name: Get tag name
              id: tag_event
              if: github.event.inputs.tag == '' || github.event.inputs.tag == null
              uses: dawidd6/action-get-tag@v1
              with:
                  strip_v: true

            # Fallback to github.event.inputs.tag if tag is empty
            - name: Fallback to github.event.inputs.tag if tag is empty
              id: tag_input
              if: github.event.inputs.tag != '' && github.event.inputs.tag != null
              run: echo "::set-output name=tag::${{ github.event.inputs.tag }}"

              # Select the tag to use
            - name: Select the tag to use
              id: tag
              run: |
                  if [ -z "${{ steps.tag_event.outputs.tag }}" ]; then
                      echo "::set-output name=tag::${{ steps.tag_input.outputs.tag }}"
                  else
                      echo "::set-output name=tag::${{ steps.tag_event.outputs.tag }}"
                  fi

            # Create manifest list and push
            - name: Create manifest list and push to Registry
              working-directory: /tmp/digests
              run: |
                  docker buildx imagetools create \
                    --tag ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
                    --tag ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.version }} \
                    --tag ${{ env.DH_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
                    --tag ${{ env.DH_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.version }} \
                    $(printf '${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}@sha256:%s ' *)

            # Inspect image
            - name: Inspect image
              run: docker buildx imagetools inspect ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
