name: Create Pre-Release on Version Change

on:
  push:
    branches:
      - v3-alpha

jobs:
  check-version-and-create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Get previous package version
        id: get_prev_version
        run: echo "::set-output name=prev_version::$(git show HEAD^:package.json | jq -r '.version')"

      - name: Get current package version
        id: get_current_version
        run: echo "::set-output name=current_version::$(jq -r '.version' package.json)"

      - name: Compare versions
        id: compare_versions
        run: |
          if [[ "${{ steps.get_prev_version.outputs.prev_version }}" != "${{ steps.get_current_version.outputs.current_version }}" ]]; then
            echo "Version changed. Creating Pre-Release."
            echo "::set-output name=version_changed::true"
          else
            echo "Version unchanged. No Pre-Release needed."
            echo "::set-output name=version_changed::false"
          fi

      - name: Create Pre-Release
        if: steps.compare_versions.outputs.version_changed == 'true'
        run: |
          # Create a new Pre-Release using GitHub API
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/:owner/:repo/releases -d '{"tag_name": "v${{ steps.get_current_version.outputs.current_version }}", "prerelease": true, "draft": false}'
