name: Sentry Release

on:
    push:
        branches:
            - "v3-beta"
        paths-ignore:
            - "**.md"
            - "**/.github/**"
            - "**/.vscode/**"
    workflow_dispatch: {}

permissions:
    packages: write
    contents: write

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

jobs:
    before_build:
        name: Create Sentry Release
        runs-on: ubuntu-latest
        steps:
            # Checkout the repo
            - name: Checkout
              uses: actions/checkout@v4

            # Get the version from the package.json
            - name: Get version
              id: get_version
              run: |
                  echo "::set-output name=version::$(jq -r '.version' package.json)"

            # Print the version
            - name: Print version
              run: |
                  echo ${{ steps.get_version.outputs.version }}

            # Create the Sentry release
            - name: Create Sentry release
              uses: getsentry/action-release@v1
              env:
                  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
                  SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
                  SENTRY_URL: https://sentry.wizarr.dev
              with:
                  environment: development
                  version: ${{ steps.get_version.outputs.version }}
                  version_prefix: "v"
                  projects: "wizarr-frontend wizarr-backend"
