name: Docker Build for LiveChat

on:
    push:
        paths-ignore:
            - "**.md"
            - "**/.github/**"
            - "**/.vscode/**"
            - "!**/apps/wizarr-livechat/**"
    workflow_dispatch: {}

permissions:
    packages: write

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: wizarr/wizarr-livechat
    IMAGE_TAG: latest

jobs:
    build_ghcr:
        name: Build Digest for GHCR
        runs-on: ubuntu-latest
        steps:
            # Checkout the repo
            - name: Checkout
              uses: actions/checkout@v4

            # Get the Metadata from the Docker Image
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

            # Set up Docker Buildx
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            # Login to GHCR
            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            # Build and push the image
            - name: Build and push
              id: build
              uses: docker/build-push-action@v5
              with:
                  context: ./apps/wizarr-livechat
                  push: true
                  platforms: linux/amd64
                  labels: ${{ steps.meta.outputs.labels }}
                  provenance: false
                  tags: |
                      ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
