name: Build Storybook

on:
    push:
        branches:
            - "beta"
        paths-ignore:
            - "!.github/workflows/build-storybook.yml"
            - "!apps/wizarr-frontend/src/**/*"
            - "!apps/wizarr-frontend/.storybook/**/*"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18.18.2

            - name: Install Dependencies
              run: npm ci --ignore-scripts

            - name: Build Storybook
              run: npx nx run wizarr-frontend:build-storybook

            - name: Deploy Storybook
              uses: peaceiris/actions-gh-pages@v3
              with:
                  external_repository: wizarrrr/storybook.wizarr.dev
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist/storybook/wizarr-frontend
                  cname: storybook.wizarr.dev
