name: Release Docker Image CI

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true

permissions:
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: wizarrrr/wizarr

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v2

      # Get the Release Version or the input version
      - name: Get the Release Version
        id: get_version
        run: |
          if [[ -z "${{ github.event.release.tag_name }}" ]]; then
            echo "::set-output name=version::${{ github.event.inputs.version }}"
          else
            echo "::set-output name=version::${{ github.event.release.tag_name }}"
          fi

      # Do not build if the release is a pre-release
      - name: Only if the release is not a pre-release
        if: github.event.release.prerelease == true
        run: exit 1

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      # Login to GHCR
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push the image
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          provenance: false
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.version }}
