name: Delete old workflow runs

on:
  push:

jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest
    name: Delete old workflow runs
    steps:
      - name: Delete workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.2.0
        id: delete-old-workflow-runs
        with:
          repository: wizarrrr/wizarr
          workflow: ".github/workflows/tailwindcss.yml"
          what-if: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
