name: Docker Build and Push

on:
  push:
    branches:
      - v3-beta

permissions:
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: wizarrrr/wizarr
  IMAGE_TAG: v3-beta

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - amd64
          - arm64

    steps:
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      # Build and push the image
      - name: Build and push for ${{ matrix.platform }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false # Do not push at this stage
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}-${{ matrix.platform }}
          platforms: linux/${{ matrix.platform }}
          outputs: type=docker,dest=/tmp/docker-image-${{ matrix.platform }}.tar

      # Upload the Artifact for docker image
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image-${{ matrix.platform }}
          path: /tmp/docker-image-${{ matrix.platform }}.tar

  push_images:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Login to GHCR
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Download Artifacts for AMD64 and ARM64
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: docker-image-amd64
          path: /tmp/docker-image-amd64.tar

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: docker-image-arm64
          path: /tmp/docker-image-arm64.tar

      # Load Images
      - name: Load Images
        run: |
          docker load -i /tmp/docker-image-amd64.tar
          docker load -i /tmp/docker-image-arm64.tar

      # Push Images
      - name: Push Images
        run: |
          docker tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}-amd64 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}-arm64 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        env:
          DOCKER_CLI_PLUGIN_BUILD: enable
