name: Build and Push Docker Image

on:
  push:
    branches:
      - v3-beta

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: wizarrrr/wizarr

jobs:
  build-and-push-image:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        platform: [linux/amd64, linux/arm64, linux/arm/v7]

    steps:
          
      # This step checks out your code repository.
      - name: Checkout repository
        uses: actions/checkout@v2

      # This step caches Docker layers to speed up the build process in subsequent workflow runs.
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /var/lib/docker
          key: docker-${{ runner.os }}-${{ github.sha }}
        
      # This step sets up QEMU for cross-architecture builds and enables Docker BuildKit.
      - name: Set up QEMU and enable BuildKit
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      # This step logs into the Docker registry using your GitHub credentials to push the Docker image.
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # This step extracts metadata like tags and labels for the Docker image.
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ github.ref_name }}

      # This step sets up Docker Buildx, which is a builder for multi-architecture Docker images.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # This step builds the Docker image using the provided Dockerfile and pushes it to the registry with specified tags and labels.
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          provenance: true
          platforms: ${{ matrix.platform }}
          tags: ${{ steps.meta.outputs.tags }}
